### ISSUE TITLE
I can't sign up for IBM, IBM requires me to verify my credit card, but I don't have a credit card 

### ISSUE THREAD

**Issue by bbcghh123** [vrtmrz/obsidian-livesync#100]
I can't sign up for IBM, IBM requires me to verify my credit card, but I don't have a credit card

**Comment by Miigon** [comment]
You can self-host the service yourself. From your repo I'm assuming you are Chinese. Purchase a cloud server from a cloud provider like tencent cloud or alicloud, then I recommend installing docker and docker-compose then use this repo to set up your service: https://github.com/vrtmrz/self-hosted-livesync-server

Noted that you will need a domain for SSL to work or otherwise you can't use it on your mobile devices.

Chinese documentation are available as well:
https://github.com/vrtmrz/obsidian-livesync/blob/main/README_cn.md
https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server_cn.md

**Comment by vrtmrz** [comment]
Thank you for your assist @Miigon!

As something other information, Couch DB can be hosted on a Raspberry Pi and we can expose it as our own dedicated server.
