### ISSUE TITLE
Cannot connect to couchdb under Android system

### ISSUE THREAD

**Issue by Asura-one** [vrtmrz/obsidian-livesync#12]
This plugin is great, but I encountered some problems in using it, I hope you can take a look at it when you have time.

I used Docker to build the couchdb service, and my PC can be synchronized normally, but my Android phone keeps prompting `could not connect to http://192.168.0.102:5984:obsidian`. I am using an Android phone to log in to http://192.168.0.102:5984/_utils/index.html and I can log in normally.

The address, username and password of couchdb are all entered correctly.

**Comment by vrtmrz** [comment]
Thank you for using this plugin! Sorry for delaying documentations.
Yes, currently this is the limitation of mobile obsidian.
This plugin and any other plugins is also could not be able to access insecure endpoint now.
In addition to, even if signed by local CA and certificate stored in device, it couldn't.
I asked in forum now. If I got new information, I'd share it.

**Comment by Asura-one** [comment]
Ok, thank you very much for your reply

**Comment by snowzach** [comment]
I have the same issue. I am using secure https on my couchdb instance with a real certificate. If there is a good way to debug this, let me know.

**Comment by vrtmrz** [comment]
I'll improve the connection test log, but if you want to see them soon, try below.

1. Connect Android device to the computer and launch inspector from chrome://inspect/#devices on PC.
2.  Choose the device and see the network pane.
3.  If the error is not caused by certificates, the error is shown on the inspector.
If the certificate is not working, the error is not shown with the straight message. we have to check the logcat.

**Comment by snowzach** [comment]
> Connect Android device to the computer and launch inspector from chrome://inspect/#devices on PC.

That helped me out. It turned out to be a DNS issue in my case. I was able to fix that and get it going. Thanks!
