### ISSUE TITLE
Folder rename case not respected

### ISSUE THREAD

**Issue by Vyeche** [vrtmrz/obsidian-livesync#130]
Hi, 

Thank you for the plugin. Loving it! :) 

Renaming the case of the folder isn't respected. So, I have to rename it for the sync to work manually.
- InputNotes -> inputNotes
- I -> i

![image](https://user-images.githubusercontent.com/972377/195114139-f1303456-8d4e-4ff2-a7bd-9cb1551197ea.png)
![image](https://user-images.githubusercontent.com/972377/195114574-1e90c39b-6d10-4c14-a9ad-212ac701f9ce.png)

Please advise.

**Comment by vrtmrz** [comment]
Thank you for finding the edge case. 
I have a bad feeling about this. We have to investigate it more, but in renaming, saving the new file is prior to deleting it by the design. (Just I wanted not to lose files even when hanged). Then, possibly we are going to lose the file. wow...

I didn't reproduce it but I thought I should tell you this.

(Of course, we can roll it back in the `History`)

Could you enable the verbose logging and check the detail of the error following the line `Could not parse`?
In the current plan, it will be fixed by changing the processing order.

**Comment by vrtmrz** [comment]
@Vyeche 
Sorry for being late. It has been fixed in case-sensitive platforms.
(Unfortunately, Windows does not respect cases. But it would not be a `Parse error` again.)

**Comment by Vyeche** [comment]
Got it, I'll test it out and see if it's okay. Thanks!

**Comment by Vyeche** [comment]
Hmm, not working, after rename. I tried opening my mobile device. Got an error.

it deleted the file on my mobile device. Then

**Comment by vrtmrz** [comment]
For future reference, #1014 now safely handles case-only file renames when the parent directory is unchanged, for example:

`Notes/Calculus.md` → `Notes/calculus.md`

It does not implement case-only folder renames. With case-insensitive filename handling enabled, an incoming change such as:

`Notes/Calculus.md` → `notes/Calculus.md`

is now deliberately refused as a file rename. The existing file and its contents remain at the old-cased path, rather than partially moving child files or leaving Obsidian's Vault cache inconsistent. The database revision may therefore remain unapplied to the Vault until the folder casing is aligned.

A complete solution requires Self-hosted LiveSync to propagate the folder rename itself and apply it as a single directory-aware operation. Moving the child files individually is not equivalent on case-insensitive file systems such as Windows.

I am leaving this historical issue closed for now, but recording here that folder case-only renames remain outside the scope of #1014.
