### ISSUE TITLE
Customization sync: allow certain files to be synced without user interaction

### ISSUE THREAD

**Issue by Ellpeck** [vrtmrz/obsidian-livesync#278]
Hi! Thanks so much again for this plugin, the new Customization Sync feature has been working incredibly well & I love the way I get to compare and pull configurations from certain devices only.

Some plugins I use (mainly Icon Folder) store things beyond their traditional "settings" in their plugin directory (like the icons assigned to each folder), and so having to sync them between devices manually using the Customization Sync modal can be a little tedious. I think it would be nice to be able to select an option for an individual file like "automatically sync between all devices", which would cause that file to be synced when customization sync runs without having to select which device to copy it from.

I'm thinking something like a button here that says "Always auto-sync":

![image](https://github.com/vrtmrz/obsidian-livesync/assets/5741138/688a1211-b9cb-4b5e-86bc-5c330701efa2)

I realize that I could use Hidden files sync for this, but having this as part of the Customization Sync system would be nice in my opinion!

**Comment by plattenschieber** [comment]
I can't see the `Configuration` Header in the `Customization Sync` pane in Version 0.19.19. Have a look here
![image](https://github.com/vrtmrz/obsidian-livesync/assets/1213794/721f05e9-1bcb-4f64-8698-8c7b5155bbae)
Am I missing something?

**Comment by Lraxer** [comment]
> I can't see the `Configuration` Header in the `Customization Sync` pane in Version 0.19.19. Have a look here ![image](https://user-images.githubusercontent.com/1213794/265972629-721f05e9-1bcb-4f64-8698-8c7b5155bbae.png) Am I missing something?

You can click the 'Open' button at the bottom to control configurations used in different devices.

**Comment by vrtmrz** [comment]
Thank you for your idea! I think that is so lovely feature!

However, we have to pack multiple files in customisation sync, due to applying theme or plugin files as a set of specific versions. Therefore, `Hidden file sync` would be more useful and efficient for synchronising such files.

Regrettably, setting up `Hidden File Sync` had been a minor hassle, especially when combined with customised synchronisation. 

Since v0.19.20, we can Ignore files on Hidden File Sync;  which were already handled in customisation sync. 
In addition to that, we can ignore specific customisation completely.
If we have configured as like this:

| key | configuration |
| --  | -- | 
| workspace.json | Ignore |
| XXX MAIN | automatically | 
| XXX DATA | selective |

Files would be handled as like this
| filename | handling method |
| -- | -- |
| workspace.json | Not synchronised |
| plugins/XXX/main.js | Hidden File Sync |
| plugins/XXX/manifest.json | Hidden File Sync |
| plugins/XXX/styles.css | Hidden File Sync |
| plugins/XXX/data.json | Customisation Sync |
| plugins/XXX/main_copy.js | Hidden File Sync |

Note: When we enable `Hidden File Sync`, `Customization sync` is temporarily disabled. Please enable it again.
I hope that v0.19.20 will help us brilliantly!

**Comment by Ellpeck** [comment]
That seems to work. Thanks so much!
