### ISSUE TITLE
How to manage device in Customization sync?

### ISSUE THREAD

**Issue by jsbyysheng** [vrtmrz/obsidian-livesync#292]
I wonder if I can manage device in Customization sync? I want to delete a device config file.

**Comment by vrtmrz** [comment]
Thank you for asking me!
I thought that I hoped to explain about `Maintenance mode`, but I found a bug that we cannot delete while all devices are even.
I will address it in a while!

**Comment by vrtmrz** [comment]
@jsbyysheng 
Hi! Sorry for being late! Since the previous version, we can delete each configuration in `Maintenance mode`.
The `Maintenance mode` can be enabled by toggling the checkbox at the bottom of the dialogue. 
After it is enabled, we can select devices even if all things are the same on each item, and a dustbin button can be shown. We can delete that by clicking this.

Also, it may be troublesome, if we have too much. We can delete all data of customization sync by `Delete all customization sync` button at the `Hatch` pane of the setting dialogue.

Would you mind trying this, please?

**Comment by jsbyysheng** [comment]
Glad to get your reply. Although Livesync is an awesome plugin, I am very busy with my school work and have no time to maintain the database. I have given up the Livesync plugin and a sync disk is used as a replacement. I'm sorry I can't help you with the testing.

**Comment by vrtmrz** [comment]
Thanks for letting me know. I am missing you a bit, but I am so happy to hear that you have found a suitable solution!
You do not have to feel sorry for anything. But I welcome you back whenever you need this plug-in again. Thank you for your contributions!
