### ISSUE TITLE
Does the IP of the database have to be bound to the domain to be used

### ISSUE THREAD

**Issue by qiang-007** [vrtmrz/obsidian-livesync#40]
Do I have to enter a domain name in the location of the URL to connect? I entered both the ipv4 and ipv6 addresses and the connection was unsuccessful! Because the user of obsidian is not a professional programmer and does not necessarily have a domain name, it is recommended to enter ipv4 or ipv6 directly.

**Comment by kenjibailly** [comment]
I have had it working without a domain name (haven't tested on mobile, just 2 pc's)
All I did was make sure the 2 pc's were on the same network as the server and I used the ip of the server this would look like something like this: 192.168.x.x

I've read in the documentation that you need https aka an ssl certification for mobile though, that's why I didn't bother testing it as I have a domain with ssl.

**Comment by vrtmrz** [comment]
@kenjibailly Thank you for your help!

@qiang-007 Short answer is "We need a domain or some solution when using this plugin on mobile. ".
It is one of the limitations of Android. SSL certificate is required and an SSL certificate is issued to the domain.

If you are serving from the local network, you can use [localhost.run](http://localhost.run/) or [ngrok](https://ngrok.com/).
And if you want to secure your content, you'll need to set it up yourself.

**Comment by vrtmrz** [comment]
Close this issue once. Feel free to open it again if you have new something.
