### ISSUE TITLE
能否增加中文支持

### ISSUE THREAD

**Issue by fu9809** [vrtmrz/obsidian-livesync#403]
这个插件很好用，非常感谢作者。
能否为这个插件增加中文支持，不会英语。

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
I am reading the kanji and using DeepL, and am answering in the atmosphere. If it is not correct, sorry in advance!

What support do you need? If that is documentation, I am so glad to accept PRs of translation!

Unfortunately, all I can do for this is keep this issue open and label it as `Help wanted`, but I am happy to do so.

Please write down what you want so that other contributors can work on it. May Chinese is fine.

**Comment by Izumiko** [comment]
fu9809 wants a Chinese UI, he doesn't speak English very well.

Is it possible to import an i18n library to provide multi-language support so that we can contribute to the translation of the UI?

**Comment by ayakasuki** [comment]
metoo ,Because this plugin is a bit complex, simple plugin settings can be in pure English, but as far as I know, this plugin has many functions and configuration options. I feel that Chinese is needed so that Chinese users can use it more conveniently. Moreover, this plugin is quite recommended among Obsidian users

**Comment by ingxhe** [comment]
me too, I need the Chinese description of the plugin function options

**Comment by vrtmrz** [comment]
Some of you have already noticed and contributed, but let me announce it.
Now Self-hosted LiveSync has an i18n feature.

We can add new translations by following the document.
[Adding translations](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/adding_translations.md)

Possibly, I will be lost about when to close this issue, so I would like to close it for now. I would be most appreciative if you could submit translation resources as new pull requests.

I would love to accept your contributions!
