### ISSUE TITLE
Remote database is 7 times larger than the vault

### ISSUE THREAD

**Issue by alx-xlx** [vrtmrz/obsidian-livesync#405]
I have a vault that has 1 plugin - livesync and around 200 notes.

The size of vault (including .obsidian dir) on windows is around 4MB but its 30MB on the couchdb.

How do I fix this ??

**Comment by vrtmrz** [comment]
Thank you for opening the issue! The shortest answer is "`Rebuild everything` may work but some overhead is needed". However, let me explain about this.

Self-hosted LiveSync splits the note into several chunks. This is for smooth synchronisation. While synchronising, only the metadata of the note and different chunks are transferred. Otherwise, we could not synchronise the vaults in Live. As you mentioned, it costs a bit overhead storage for each chunk.

However, chunks are shared between multiple notes if their content is the same. Therefore, finally, usage does not depend on the total size but on the content.
Therefore, for small vaults, this may be a particularly worrying magnification. However, in larger vaults, this will gradually become less of a concern.

Up to this point, everything works well for long-term use. However, there is one aspect that requires further consideration. -- Self-hosted LiveSync will not delete any unused chunks.

In order to synchronise, we need to detect and resolve conflicts that have occurred in the past in view of the point of synchronisation. Hence, we cannot delete the old things without dropping these chances. This is not sure by every automatic decision except for the vault owner. (For this sake, we can lock the remote database and force the other devices to fetch when we have rebuilt it).

Ultimately, rebuilding databases (both local and remote databases) shrinks the CouchDB. Other methods are palliative methods.

**Comment by vrtmrz** [comment]
To reduce the total database sizes, two features have been implemented. However, they are still experimental features. After it has become stable, they will help to reduce storage sizes.

- Incubate chunks in Document
When enabling this feature, the chunks which have not stabilised will not be made as independent chunks. Setting `_revs_limit` and performing compaction might shrink the database size.
- Automatic data compression
While sending or receiving notes and chunks, automatically compress the data to reduce the traffic and storage sizes. However, this might be less effective given storage size if the CouchDB is configured as using `file_compression`.

I would like to close this Issue in the hope that these features will be effective. Please feel free to reopen this!
