### ISSUE TITLE
unable to setup Customization Sync

### ISSUE THREAD

**Issue by alx-xlx** [vrtmrz/obsidian-livesync#435]
The customization sync doesn't register the name I input during setup.
I have two devices "Ideapad" as the main device and "macMiniM2" as the subsequent device

For example in this clip, the device name I had setup as "Ideapad" but now it went back to "desktop" and I can't even switch it off, I tried restarting the browser. But I now asked to "Configure the device name" but I am unable to do it.

Same issue I faced on the other device. I tried restarting both the device but that didn't help. Something is wrong with the plugin.

![](https://i.imgur.com/z0bOego.gif)

**Comment by alx-xlx** [comment]
I have also tried Minimal setup as the steps here https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/quick_setup.md#2-minimal-setup

But all the fields are disabled, doesn't make any sense why that would be the case, I haven't even enabled the "Customization sync" but it still shows in the toolbar.

![](https://i.imgur.com/rrdc1dq.gif)

**Comment by vrtmrz** [comment]
Thank you for pointing out to me! And sorry for your inconvenience.

Both were completely missed. All your help and kindness keep the peace in Self-hosted LiveSync. I appreciate you so much!

Fixed in v0.23.10. Would you mind if I ask you to check the latest version, please?

**Comment by alx-xlx** [comment]
yes it works well now.

However I wish to know how to keep plugins in sync between different devices. I am faced with this option here.
It asks for **hidden file synchronization** or **customization sync** but I don't see the options to select those, instead I see **Fetch** and **Custom**. What should i select in different devices.
![](https://i.imgur.com/RdOvrRk.png)

**Comment by alx-xlx** [comment]
@vrtmrz 
I am trying to sync between two devices, apple and ideapad. the current clips are from "ideapad"

I had installed a plugin (Templater) on "apple" but when i apply those on "ideapad" it faults and the this is how it looks

### failure to retain the device name
### plugins don't sync properly

![](https://i.imgur.com/pSGmZFH.gif)

**Comment by alx-xlx** [comment]
@vrtmrz 
hey i tested the v0.23.11 
The plugins are syncing well along with their data.

However there is issue when I Sync the configuration from a 2nd subsequent device to the main device then I get the "configure device name" **BUG**

https://i.imgur.com/A5iViJu.gif

**Comment by alx-xlx** [comment]
I see the when we copy the setup URI to 2nd device then plugins are not properly synced to the 2nd device, but once I install some random plugin on the main device and then try to "Custom Sync" again then it detects the changes and all the plugins are synced to the 2nd device.

Similarly I see the same issue for the Left Toolbar/ Ribbon, I arrange them properly on the main device but they too don't get synced on the first try, instead on the main device I have to edit/rearrage one plugin and then when I try to sync to 2nd device again then it detects the changes and then syncs.

I see these issues with the `app.json appearance.json, community-plugins.json, core-plugins-migration.json, core-plugins.json, workspace.json` at least these are the ones I saw misbehaving

As you can see in this clip of the main device trying to get the Custom sync from 2nd device, I had made no changes to anything on the 2nd device (only enabled Custom sync), but it seems the data got manipulated somewhere.

https://i.imgur.com/CVmPzIg.gif
![](https://i.imgur.com/CVmPzIg.gif)

**Comment by alx-xlx** [comment]
## Sync from Mobile to PC - **Bugged**
1. some plugins are not compatible with mobile devices and are automatically disabled on mobile device. The issue is that when we sync the main device with such mobile device the plugins also gets disabled from the main device.
2. This issue also extends to the status bar, since there are no status bar on mobile, the status bar for main device gets corrupted when we sync from mobile to PC.
3. The left toolbar also don't get synced properly, we have to rearrange them manually again

**Comment by slimjet4u** [comment]
I think the custom sync is not usable at all, update after update new errors happen, or previous solved errors come back. I would not recommend using it. I think it is not a priority for the devs at the moment.

**Comment by vrtmrz** [comment]
Sorry for being late!
@alx-xlx 

One possibility is that chunks of these files have been already broken. In the previous (you have reported) version, chunks sometimes had been conflicted on CouchDB. 
This problem does not happen on the latest version, but chunks which already been made will not be purged. This is not something that normally happens, so it is not possible to remove this corrupted chunk without performing `Rebuild everything ` once.
I am so sorry to ask you to do this as it takes a bit of time but try `Rebuild everything` once.

> Sync from Mobile to PC - BUG

I think this is more serious. Does it mean that non selected thing have been overwritten? It would be nice to share the logs, please.

Or, `Select All Shiny` does not care about compatibility, so we cannot use the button if both mobile and desktop devices exist. 
We should need a new feature -- a setting of device platform, and `Select all shiny on the same platform`. If you are using `Select All Shiny` and have got trouble, I will implement it! 
Please make a new feature request.

@slimjet4u 
Unfortunately, you are correct, and possibly that means I do not use these features in the same scenario as you do. (for example, I do not use `Select All Shiny` and `Apply All` at the same time). 
Many features have so many flexibilities. Hence our issue report template begins with `Expected behaviour`, `Actually happened`, and, `Reproducing procedure`.
I am sure I am simply missing something, as I think I have been checking the functionality (in my usage). Please point me to anything you have noticed!

**Comment by alx-xlx** [comment]
@vrtmrz 
I am using a completely new vault to test these, and still on the latest version there are issues like `unable to configure the device name` that issue still exists on the 0.23.13.

I was hoping that the customization sync to be an out of the box feature that would be easy to use, but it seems we have to manually configure everything during each sync, I think that's not possible to do when there are 40+ plugins and multiple devices.

Anyways, thanks for your quick valuable responses though, sorry for the trouble

**Comment by vrtmrz** [comment]
I am very sorry that this Issue could not be resolved. I would like to thank you once again for your patience.

Next time you submit an Issue, I would be grateful if you could take some time to filled the issue template and share the log and the report which can be made by the `Make report` button. It should be helpful for us. However, all of your clips were so useful! 

I appreciate all of your contributions!
