### ISSUE TITLE
Android: live sync long startup

### ISSUE THREAD

**Issue by foegra** [vrtmrz/obsidian-livesync#438]
It takes a couple of minutes on my android device in order for sync to start after launching Obsidian.

After around 30 seconds - I can trigger "Replicate now" which does make a sync (until then even manually triggering nothing happens) and then goes to stop mode again. 

Eventually live sync starts, after couple of minutes waiting, which is not optimal. Seems like live sync is waiting for something. With the same sonfig - there is no such an issue on desktops.

Using 0.23.11 version.

**Comment by Facni** [comment]
When this started to happen?

**Comment by Facni** [comment]
I have just tested in my device and it seems to work properly.

**Comment by foegra** [comment]
> I have just tested in my device and it seems to work properly for me.

Is there a way to provide troubleshooting data? Even if I enable verbose log - there is nothing during the downtime period except "scanning hidden files" couple of time.

**Comment by vrtmrz** [comment]
Sorry for the delay. I may have something a bit closer to an answer (That is because I have also wondered). Have you by any chance installed and enabled DataView?

I also enabled DataView after a long time, but also in my environment now, apparently, it seems to be locking something at startup, and Self-hosted LiveSync cannot open the local database until DataView is initialised.

Would you check if disabling DataView makes the situation better? I have assumed it was a problem with my environment.
If it gets better, I will address to make them can be coexist.

**Comment by foegra** [comment]
Well, I've changed firmware now from HyperOS to AOSP based ROM and problem is gone. Loads fast.
