### ISSUE TITLE
Backblaze B2 storage error

### ISSUE THREAD

**Issue by 0dragosh** [vrtmrz/obsidian-livesync#463]
I'm trying to setup S3 storage with Backblaze B2.

I'm getting the following errors when testing the connection:

Error! Could not connect to: https://s3.us-west-000.backblazeb2.com
TypeError:failed to fetch

Any pointers? I would look for more logs but I don't know where those would be in an obsidian plugin.

**Comment by rhld16** [comment]
First goal would be to check if you can connect to https://s3.us-west-000.backblazeb2.com/ at all on your system. But the more likely issue is that you're getting an error from CORS.
You can follow the guide [here](https://www.backblaze.com/blog/crash-cors-a-guide-for-using-cors/) in order to add CORS support to your bucket, making sure to add "app://obsidian" specifically and the other URLs mentioned in the plugin's setup guide.

**Comment by 0dragosh** [comment]
Hi @rhld16, thanks for the help.

Setting CORS on the bucket to allow everything didn't work, but turning on "Use Custom HTTP Handler" did.

Thanks again.

**Comment by alan16742** [comment]
I encountered the same error when using Alibaba Cloud S3, but it could not be solved using "Use Custom HTTP Handler". Maybe 
because the plug-in uses `https://s3.amazoneaws.com/*/` instead of `https://*.s3.amazoneaws.com`
