### ISSUE TITLE
how to resolve all conflicts one time?

### ISSUE THREAD

**Issue by whitewatercn** [vrtmrz/obsidian-livesync#498]
# Abstract
There are many conflicts in the logs, and resolving them one by one can be tedious, how can i deal with them one time , just overwrite with a new edition?

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/5eda9932-8cdd-4632-bdb1-57359be6e3f0">

**Comment by vrtmrz** [comment]
Thank you for asking me! 
This might be fixed by enabling `Always overwrite with a new file` and restarting Obsidian, and if not enough, performing `Fetch` the remote database again. 

Or if you have any `correct` device, rebuilding the databases from the device is more recommended. Then, the rebuilt database will be transferred to the other devices. 

Please keep in mind that conflicts are also kept in the remote database. Therefore, without resolving the conflicts, only fetching will not resolve the situation.

I hope that this will help you!

**Comment by whitewatercn** [comment]
> Thank you for asking me! This might be fixed by enabling `Always overwrite with a new file` and restarting Obsidian, and if not enough, performing `Fetch` the remote database again.
> 
> Or if you have any `correct` device, rebuilding the databases from the device is more recommended. Then, the rebuilt database will be transferred to the other devices.
> 
> Please keep in mind that conflicts are also kept in the remote database. Therefore, without resolving the conflicts, only fetching will not resolve the situation.
> 
> I hope that this will help you!

thanks for your reply, i will have a try to rebuild my remote database and test to sync again
